name: 燕云十六声自动任务

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间9点运行
  workflow_dispatch:  # 支持手动触发

jobs:
  auto-task:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 运行签到脚本
      env:
        yysls_miniapp: ${{ secrets.YYSLS_MINIAPP }}
        push_plus_token: ${{ secrets.PUSH_PLUS_TOKEN }}
      run: |
        python 签到.py
    
    - name: 运行云游脚本
      env:
        yysls_yunyouji: ${{ secrets.YYSLS_YUNYOUJI }}
        push_plus_token: ${{ secrets.PUSH_PLUS_TOKEN }}
      run: |
        python 云游.py 
